<?php
/**
 * Product list toolbar template - Custom Toyota Brand Store PLP
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php 
    $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products custom-plp-toolbar <?= $block->getIsBottom() ? 'toolbar-bottom' : 'toolbar-top' ?>" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <div class="toolbar-pager-wrapper">
                <?= $block->getPagerHtml() ?>
            </div>
            <div class="toolbar-limiter-wrapper">
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
            </div>
        <?php else: ?>
            <div class="toolbar-amount-wrapper">
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            </div>
            <?php if ($block->isExpanded()): ?>
                <div class="toolbar-sorter-wrapper">
                    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
                </div>
            <?php endif ?>
        <?php endif ?>
    </div>
<?php endif ?>
