<?php
/**
 * Product list toolbar sorter template
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter plp-sorter-container">
    <div class="sorter-select-wrapper">
        <span class="sorter-prefix"><?= $block->escapeHtml(__('Sort by:')) ?></span>
        <select id="sorter" data-role="sorter" class="sorter-options plp-sort-select">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isOrderCurrent($_key)) :?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <span class="sorter-arrow">
            <svg width="10" height="6" viewBox="0 0 10 6" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M1 1L5 5L9 1" stroke="#374151" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </span>
    </div>
</div>
